### ISSUE TITLE
Importing overly causes ImportError: cannot import name 'POLLRDHUP' from 'select'

### ISSUE THREAD

**Issue by kbakk** [theelous3/overly#2]
When trying to import overly, I run into an error:

```
$ python3
Python 3.7.5 (default, Nov  1 2019, 02:16:32)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import overly
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/overly/venv/lib/python3.7/site-packages/overly/__init__.py", line 2, in <module>
    from .base import Server, ClientHandler
  File "/private/tmp/overly/venv/lib/python3.7/site-packages/overly/base.py", line 15, in <module>
    from .constants import HttpMethods, PollMaskGroups
  File "/private/tmp/overly/venv/lib/python3.7/site-packages/overly/constants.py", line 2, in <module>
    from select import POLLIN, POLLPRI, POLLOUT, POLLERR, POLLHUP, POLLRDHUP, POLLNVAL
ImportError: cannot import name 'POLLRDHUP' from 'select' (/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/select.cpython-37m-darwin.so)
```

I first suspected my Python installation, but it happens on my colleagues computer as well. I'm running MacOS Mojave 10.14.6.

**Comment by nm17** [comment]
Almost the same error on Python 3.9:
```
Traceback (most recent call last):
  File "[...]\tests\test_login.py", line 1, in <module>
    import overly
  File "[...]\venv\lib\site-packages\overly\__init__.py", line 2, in <module>
    from .base import Server, ClientHandler
  File "[...]\venv\lib\site-packages\overly\base.py", line 6, in <module>
    from select import poll
ImportError: cannot import name 'poll' from 'select' (C:\Users\admin\AppData\Local\Programs\Python\Python39\DLLs\select.pyd)
```

**Comment by nm17** [comment]
@theelous3

**Comment by nonsleepr** [comment]
This is still an issue a year later. :(

**Comment by BegicHarun** [comment]
Hello,

I had a same problem and i solve it when i put 'from select import *'

I hope it will work for you!
